//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tb_filme
    {
        public int Id { get; set; }
        public string Nome { get; set; }
        public string Lancamento { get; set; }
        public Nullable<short> Nota { get; set; }
        public int Diretor { get; set; }
    
        public virtual tb_diretor tb_diretor { get; set; }
    }
}
